// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVvhGeKHorw7fJwy3Z9idQkExZIU4jTtQ',
    appId: '1:149715164888:web:dd6ea2425dab3d184d81ad',
    messagingSenderId: '149715164888',
    projectId: 'sign-pain',
    authDomain: 'sign-pain.firebaseapp.com',
    storageBucket: 'sign-pain.firebasestorage.app',
    measurementId: 'G-9LBGPDC7V6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbK-2cl6FigiTJN92oCr3-HDGCrFyfqrc',
    appId: '1:149715164888:android:d3e6ad32f6cb8b304d81ad',
    messagingSenderId: '149715164888',
    projectId: 'sign-pain',
    storageBucket: 'sign-pain.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDt7dEan0YgW5d_38JzNgnAwLzvPjFibl0',
    appId: '1:149715164888:ios:f6d5ffcabc224e554d81ad',
    messagingSenderId: '149715164888',
    projectId: 'sign-pain',
    storageBucket: 'sign-pain.firebasestorage.app',
    iosBundleId: 'com.example.signPain',
  );

}